#ifndef CYGONCE_PKGCONF_HAL_CORTEXM_KINETIS_TWR_K60N512_H
#define CYGONCE_PKGCONF_HAL_CORTEXM_KINETIS_TWR_K60N512_H
/*
 * File <pkgconf/hal_cortexm_kinetis_twr_k60n512.h>
 *
 * This file is generated automatically by the configuration
 * system. It should not be edited. Any changes to this file
 * may be overwritten.
 */

#define HAL_PLATFORM_CPU    "Cortex-M4"
#define HAL_PLATFORM_BOARD  "Freescale TWR-K60N512"
#define HAL_PLATFORM_EXTRA  ""
#define CYG_HAL_STARTUP_PLF MRAM
#define CYG_HAL_STARTUP_PLF_MRAM
#define CYGHWR_HAL_CORTEXM_KINETIS_PLF_XTAL_OR_OSC_FREQ 50000000
#define CYGHWR_HAL_CORTEXM_KINETIS_PLF_XTAL_OR_OSC_FREQ_50000000
#define CYGHWR_HAL_CORTEXM_KINETIS_PLF_RTC 1
#define CYGNUM_HAL_VIRTUAL_VECTOR_COMM_CHANNELS 1
#define CYGNUM_HAL_VIRTUAL_VECTOR_COMM_CHANNELS_1
#define CYGNUM_HAL_VIRTUAL_VECTOR_DEBUG_CHANNEL 0
#define CYGNUM_HAL_VIRTUAL_VECTOR_DEBUG_CHANNEL_0
#define CYGNUM_HAL_VIRTUAL_VECTOR_CONSOLE_CHANNEL 0
#define CYGNUM_HAL_VIRTUAL_VECTOR_CONSOLE_CHANNEL_0
#define CYGNUM_HAL_VIRTUAL_VECTOR_CONSOLE_CHANNEL_BAUD 38400
#define CYGNUM_HAL_VIRTUAL_VECTOR_CONSOLE_CHANNEL_BAUD_38400
#define CYGNUM_HAL_VIRTUAL_VECTOR_DEBUG_CHANNEL_BAUD 38400
#define CYGNUM_HAL_VIRTUAL_VECTOR_DEBUG_CHANNEL_BAUD_38400
#define CYGBLD_GLOBAL_OPTIONS 1
#define CYGSEM_HAL_USE_ROM_MONITOR GDB_stubs
#define CYGSEM_HAL_USE_ROM_MONITOR_GDB_stubs

#endif
