#ifndef CYGONCE_PKGCONF_HAL_CORTEXM_H
#define CYGONCE_PKGCONF_HAL_CORTEXM_H
/*
 * File <pkgconf/hal_cortexm.h>
 *
 * This file is generated automatically by the configuration
 * system. It should not be edited. Any changes to this file
 * may be overwritten.
 */

#define CYGINT_HAL_CORTEXM_BIGENDIAN 0
#define CYGINT_HAL_CORTEXM_BIGENDIAN_0
#define CYGHWR_HAL_CORTEXM M4
#define CYGHWR_HAL_CORTEXM_M4
#define CYGHWR_HAL_CORTEXM_SYSTICK_CLK_SOURCE INTERNAL
#define CYGHWR_HAL_CORTEXM_SYSTICK_CLK_SOURCE_INTERNAL
#define CYGINT_HAL_CORTEXM_FPU 0
#define CYGINT_HAL_CORTEXM_FPU_0
#define CYGIMP_HAL_ARCH_ENDIAN 1
#define CYGNUM_HAL_CORTEXM_PRIORITY_MAX 16
#define CYGNUM_HAL_CORTEXM_PRIORITY_MAX_16
#define CYGNUM_HAL_BREAKPOINT_LIST_SIZE 8
#define CYGNUM_HAL_BREAKPOINT_LIST_SIZE_8

#endif
