#ifndef CYGONCE_PKGCONF_ISOINFRA_H
#define CYGONCE_PKGCONF_ISOINFRA_H
/*
 * File <pkgconf/isoinfra.h>
 *
 * This file is generated automatically by the configuration
 * system. It should not be edited. Any changes to this file
 * may be overwritten.
 */

#define CYGINT_ISO_MAIN_STARTUP 0
#define CYGINT_ISO_MAIN_STARTUP_0
#define CYGINT_ISO_ENVIRON 0
#define CYGINT_ISO_ENVIRON_0
#define CYGINT_ISO_CTYPE 1
#define CYGINT_ISO_CTYPE_1
#define CYGINT_ISO_ERRNO_CODES 1
#define CYGINT_ISO_ERRNO_CODES_1
#define CYGBLD_ISO_ERRNO_CODES_HEADER <cyg/error/codes.h>
#define CYGINT_ISO_ERRNO 1
#define CYGINT_ISO_ERRNO_1
#define CYGBLD_ISO_ERRNO_HEADER <cyg/error/errno.h>
#define CYGINT_ISO_LOCALE 1
#define CYGINT_ISO_LOCALE_1
#define CYGINT_ISO_STDLIB_STRCONV 1
#define CYGINT_ISO_STDLIB_STRCONV_1
#define CYGINT_ISO_STDLIB_STRCONV_FLOAT 1
#define CYGINT_ISO_STDLIB_STRCONV_FLOAT_1
#define CYGINT_ISO_RAND 1
#define CYGINT_ISO_RAND_1
#define CYGINT_ISO_MALLOC 1
#define CYGINT_ISO_MALLOC_1
#define CYGINT_ISO_MALLINFO 1
#define CYGINT_ISO_MALLINFO_1
#define CYGINT_ISO_EXIT 0
#define CYGINT_ISO_EXIT_0
#define CYGINT_ISO_STDLIB_ENVIRON 1
#define CYGINT_ISO_STDLIB_ENVIRON_1
#define CYGINT_ISO_STDLIB_SYSTEM 1
#define CYGINT_ISO_STDLIB_SYSTEM_1
#define CYGINT_ISO_BSEARCH 1
#define CYGINT_ISO_BSEARCH_1
#define CYGINT_ISO_QSORT 1
#define CYGINT_ISO_QSORT_1
#define CYGINT_ISO_ABS 1
#define CYGINT_ISO_ABS_1
#define CYGINT_ISO_DIV 1
#define CYGINT_ISO_DIV_1
#define CYGINT_ISO_STDLIB_MULTIBYTE 1
#define CYGINT_ISO_STDLIB_MULTIBYTE_1
#define CYGBLD_ISO_STRERROR_HEADER <cyg/error/strerror.h>
#define CYGINT_ISO_STRTOK_R 1
#define CYGINT_ISO_STRTOK_R_1
#define CYGBLD_ISO_STRTOK_R_HEADER <cyg/libc/string/string.h>
#define CYGINT_ISO_STRING_LOCALE_FUNCS 1
#define CYGINT_ISO_STRING_LOCALE_FUNCS_1
#define CYGBLD_ISO_STRING_LOCALE_FUNCS_HEADER <cyg/libc/string/string.h>
#define CYGINT_ISO_STRING_BSD_FUNCS 1
#define CYGINT_ISO_STRING_BSD_FUNCS_1
#define CYGBLD_ISO_STRING_BSD_FUNCS_HEADER <cyg/libc/string/bsdstring.h>
#define CYGINT_ISO_STRING_MEMFUNCS 1
#define CYGINT_ISO_STRING_MEMFUNCS_1
#define CYGBLD_ISO_STRING_MEMFUNCS_HEADER <cyg/libc/string/string.h>
#define CYGINT_ISO_STRING_STRFUNCS 1
#define CYGINT_ISO_STRING_STRFUNCS_1
#define CYGBLD_ISO_STRING_STRFUNCS_HEADER <cyg/libc/string/string.h>
#define CYGINT_ISO_SIGNAL_NUMBERS 0
#define CYGINT_ISO_SIGNAL_NUMBERS_0
#define CYGINT_ISO_SIGNAL_IMPL 0
#define CYGINT_ISO_SIGNAL_IMPL_0
#define CYGINT_POSIX_REALTIME_SIGNALS 0
#define CYGINT_POSIX_REALTIME_SIGNALS_0
#if CYGINT_POSIX_REALTIME_SIGNALS
# define _POSIX_REALTIME_SIGNALS 1
#endif
#define CYGINT_ISO_SETJMP 0
#define CYGINT_ISO_SETJMP_0
#define CYGINT_ISO_SIGSETJMP 0
#define CYGINT_ISO_SIGSETJMP_0
#define CYGINT_ISO_FCNTL 0
#define CYGINT_ISO_FCNTL_0
#define CYGINT_ISO_OPEN 0
#define CYGINT_ISO_OPEN_0
#define CYGINT_ISO_DIRENT 0
#define CYGINT_ISO_DIRENT_0
#define CYGINT_ISO_PTHREADTYPES 0
#define CYGINT_ISO_PTHREADTYPES_0
#define CYGINT_ISO_PMUTEXTYPES 0
#define CYGINT_ISO_PMUTEXTYPES_0
#define CYGINT_ISO_BSDTYPES 0
#define CYGINT_ISO_BSDTYPES_0
#define CYGINT_ISO_SCHED_IMPL 0
#define CYGINT_ISO_SCHED_IMPL_0
#define CYGINT_ISO_SEMAPHORES 0
#define CYGINT_ISO_SEMAPHORES_0
#if CYGINT_ISO_SEMAPHORES
# define _POSIX_SEMAPHORES 1
#endif
#define CYGINT_ISO_MQUEUE 0
#define CYGINT_ISO_MQUEUE_0
#if CYGINT_ISO_MQUEUE
# define _POSIX_MESSAGE_PASSING 1
#endif
#define CYGINT_ISO_POSIX_LIMITS 0
#define CYGINT_ISO_POSIX_LIMITS_0
#define CYGINT_ISO_TERMIOS 0
#define CYGINT_ISO_TERMIOS_0
#define CYGINT_ISO_DLFCN 0
#define CYGINT_ISO_DLFCN_0

#endif
