#ifndef CYGONCE_PKGCONF_SYSTEM_H
#define CYGONCE_PKGCONF_SYSTEM_H
/*
 * File <pkgconf/system.h>
 *
 * This file is generated automatically by the configuration
 * system. It should not be edited. Any changes to this file
 * may be overwritten.
 */

#define CYGNUM_VERSION_CURRENT 0x7fffff00
#define CYGPKG_HAL_CORTEXM current
#define CYGPKG_HAL_CORTEXM_current
#define CYGNUM_HAL_CORTEXM_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_HAL_CORTEXM_VERSION_MINOR -1
#define CYGNUM_HAL_CORTEXM_VERSION_RELEASE -1
#define CYGBLD_HAL_ENDIAN_H <cyg/hal/cortexm_endian.h>
#define CYGPKG_HAL_CORTEXM_KINETIS current
#define CYGPKG_HAL_CORTEXM_KINETIS_current
#define CYGNUM_HAL_CORTEXM_KINETIS_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_HAL_CORTEXM_KINETIS_VERSION_MINOR -1
#define CYGNUM_HAL_CORTEXM_KINETIS_VERSION_RELEASE -1
#define CYGBLD_HAL_TARGET_H   <pkgconf/hal_cortexm.h>
#define CYGBLD_HAL_VARIANT_H  <pkgconf/hal_cortexm_kinetis.h>
#define CYG_HAL_STARTUP MRAM
#define CYG_HAL_STARTUP_MRAM
#define CYGHWR_MEMORY_LAYOUT_LDI <pkgconf/mlt_kinetis_unisram_mram.ldi>
#define CYGHWR_MEMORY_LAYOUT_H <pkgconf/mlt_kinetis_unisram_mram.h>
#define CYGPKG_HAL_CORTEXM_KINETIS_TWR_K60N512_MRAM current
#define CYGPKG_HAL_CORTEXM_KINETIS_TWR_K60N512_MRAM_current
#define CYGNUM_HAL_CORTEXM_KINETIS_TWR_K60N512_MRAM_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_HAL_CORTEXM_KINETIS_TWR_K60N512_MRAM_VERSION_MINOR -1
#define CYGNUM_HAL_CORTEXM_KINETIS_TWR_K60N512_MRAM_VERSION_RELEASE -1
#define CYGBLD_HAL_PLATFORM_H <pkgconf/hal_cortexm_kinetis_twr_k60n512.h>
#define CYGPKG_IO_SERIAL_FREESCALE_UART_HDR current
#define CYGPKG_IO_SERIAL_FREESCALE_UART_HDR_current
#define CYGNUM_IO_SERIAL_FREESCALE_UART_HDR_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_IO_SERIAL_FREESCALE_UART_HDR_VERSION_MINOR -1
#define CYGNUM_IO_SERIAL_FREESCALE_UART_HDR_VERSION_RELEASE -1
/***** serial driver proc output start *****/
#define CYGDAT_IO_SERIAL_DEVICE_HDR_HEADER <pkgconf/io_serial_freescale_uart_hdr.h>
/*****  serial driver proc output end  *****/
#define CYGPKG_HAL current
#define CYGPKG_HAL_current
#define CYGNUM_HAL_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_HAL_VERSION_MINOR -1
#define CYGNUM_HAL_VERSION_RELEASE -1
#define CYGPKG_INFRA current
#define CYGPKG_INFRA_current
#define CYGNUM_INFRA_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_INFRA_VERSION_MINOR -1
#define CYGNUM_INFRA_VERSION_RELEASE -1
#define CYGPKG_KERNEL current
#define CYGPKG_KERNEL_current
#define CYGNUM_KERNEL_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_KERNEL_VERSION_MINOR -1
#define CYGNUM_KERNEL_VERSION_RELEASE -1
#define CYGPKG_ERROR current
#define CYGPKG_ERROR_current
#define CYGNUM_ERROR_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_ERROR_VERSION_MINOR -1
#define CYGNUM_ERROR_VERSION_RELEASE -1
#define CYGPKG_MEMALLOC current
#define CYGPKG_MEMALLOC_current
#define CYGNUM_MEMALLOC_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_MEMALLOC_VERSION_MINOR -1
#define CYGNUM_MEMALLOC_VERSION_RELEASE -1
#define CYGPKG_LIBC_STRING current
#define CYGPKG_LIBC_STRING_current
#define CYGNUM_LIBC_STRING_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_LIBC_STRING_VERSION_MINOR -1
#define CYGNUM_LIBC_STRING_VERSION_RELEASE -1
#define CYGPKG_ISOINFRA current
#define CYGPKG_ISOINFRA_current
#define CYGNUM_ISOINFRA_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_ISOINFRA_VERSION_MINOR -1
#define CYGNUM_ISOINFRA_VERSION_RELEASE -1
#define CYGPKG_CPULOAD current
#define CYGPKG_CPULOAD_current
#define CYGNUM_CPULOAD_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_CPULOAD_VERSION_MINOR -1
#define CYGNUM_CPULOAD_VERSION_RELEASE -1
#define CYGPKG_LIBC_I18N current
#define CYGPKG_LIBC_I18N_current
#define CYGNUM_LIBC_I18N_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_LIBC_I18N_VERSION_MINOR -1
#define CYGNUM_LIBC_I18N_VERSION_RELEASE -1
#define CYGPKG_LIBC_STDLIB current
#define CYGPKG_LIBC_STDLIB_current
#define CYGNUM_LIBC_STDLIB_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_LIBC_STDLIB_VERSION_MINOR -1
#define CYGNUM_LIBC_STDLIB_VERSION_RELEASE -1
#define CYGPKG_LIBM current
#define CYGPKG_LIBM_current
#define CYGNUM_LIBM_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_LIBM_VERSION_MINOR -1
#define CYGNUM_LIBM_VERSION_RELEASE -1

#endif
