#variable for user project
COMPILER_CC='i386-elf-gcc'
COMPILER_CXX='i386-elf-g++'
ARCHIVER='i386-elf-ar'
#ARCHIVE_INDEXER='randlib'
ARCH='CPU_GNU32'
PLATEFORME='synthetic/x86/'
TARGET_SUFFIX='synthetic'
OPTS_APP='-O0'
DEBUG_LEVEL='-gdwarf-2 -g3'
NANOX=1
FONTS_NANOX='FONT_VERA'
#FONTS_NANOX='FONT_MEDIUM,FONT_MEDIUM_JA,FONT_METRIX_SYMBOLS,FONT_VERA,FONT_VERA_BD,FONT_ARIAL_UNICODE'
LWIP=1
OPTS_LWIP='-O2'
VERBOSE=0
STRIP=0
TINYGL=0
