#python module
import os

#We need common file
#directories
at91m55800a_base_dir = os.getenv('HOME') + '/tauon/sys/root/'
at91m55800a_prj_dir = at91m55800a_base_dir + 'prj/scons/'

#import common scons script
SConscript([at91m55800a_prj_dir + 'common/SConscript'])

#import common src list files
Import('common_tauon_src_list')

#directories of source file
tauon_src_dir = at91m55800a_base_dir + 'src/'
tauon_kernel_dir = tauon_src_dir + 'kernel/'
tauon_kernel_arch_dir = tauon_kernel_dir + 'core/arch/arm/'
tauon_kernel_dev_dir = tauon_kernel_dir + 'dev/'
tauon_kernel_dev_at91m55800a_dir = tauon_kernel_dev_dir + 'arch/arm7/at91m55800a/'

#get previous files
tauon_kernel_src_list = common_tauon_src_list

#arch config files
tauon_kernel_src_list.extend([tauon_kernel_arch_dir+'dev_mkconf.c',
tauon_kernel_arch_dir+'bin_mkconf.c', tauon_kernel_arch_dir+'dev_dskimg.c'
])

#arch specific function
tauon_kernel_src_list.extend([tauon_kernel_dir+'core/core-ecos/arch/arm/memcpy.S',
tauon_kernel_dir+'core/core-ecos/arch/arm/memmove.S',
tauon_kernel_dir+'core/core-ecos/arch/arm/memset.S'
])

#device files
tauon_kernel_src_list.extend([tauon_kernel_dev_at91m55800a_dir+'dev_at91m55800a_uart_s0/dev_at91m55800a_uart_s0.c',
tauon_kernel_dev_at91m55800a_dir+'dev_at91m55800a_rtc/dev_at91m55800a_rtc.c',
])

#directory to store lib
tauon_ecos_lib_dir = at91m55800a_base_dir + 'lib/arch/arm7/at91m55800a/'
tauon_ecos_install_dir = tauon_ecos_lib_dir + 'install/'

tauon_kernel_lib_dir = tauon_ecos_lib_dir + 'bin/'
tauon_kernel_obj_dir = at91m55800a_prj_dir + 'arch/arm7/at91m55800a/obj/'

#export source files
Export('tauon_kernel_src_list')
Export('tauon_kernel_lib_dir')
Export('tauon_kernel_obj_dir')
Export('tauon_ecos_install_dir')
