#python module
import os
from tauon import *

#We need common file
#directories
k60n512_base_dir = os.getenv('HOME') + '/tauon/sys/root/'
k60n512_prj_dir = k60n512_base_dir + 'prj/scons/'

#import common scons script
SConscript([k60n512_prj_dir + 'common/SConscript'])

#import common src list files
Import('common_tauon_src_list')

#directories of source file
tauon_src_dir = k60n512_base_dir + 'src/'
tauon_kernel_dir = tauon_src_dir + 'kernel/'
tauon_kernel_arch_dir = tauon_kernel_dir + 'core/arch/cortexm/'
tauon_kernel_dev_dir = tauon_kernel_dir + 'dev/'
tauon_kernel_dev_k60n512_dir = tauon_kernel_dev_dir + 'arch/cortexm/k60n512/'
tauon_sbin_dir = tauon_src_dir + 'sbin/'

#get previous files
tauon_kernel_src_list = common_tauon_src_list

#sbin special case for init
tauon_kernel_src_list.extend([TauonSource(tauon_sbin_dir+'initd.c')])

#arch config files
tauon_kernel_src_list.extend([TauonSource(tauon_kernel_arch_dir+'dev_mkconf.c'),
TauonSource(tauon_kernel_arch_dir+'bin_mkconf.c'),
TauonSource(tauon_kernel_arch_dir+'dev_dskimg.c')
])

#device files
tauon_kernel_src_list.extend([TauonSource(tauon_kernel_dev_k60n512_dir+'dev_k60n512_uart_s3/dev_k60n512_uart_s3.c'),
TauonSource(tauon_kernel_dev_k60n512_dir+'dev_k60n512_rtc/dev_k60n512_rtc.c'),
TauonSource(tauon_kernel_dev_k60n512_dir+'dev_k60n512_enet/dev_k60n512_enet.c'),
])

#directory to store lib
tauon_ecos_lib_dir = k60n512_base_dir + 'lib/arch/cortexm/k60n512/'
tauon_ecos_install_dir = tauon_ecos_lib_dir + 'install/'

tauon_kernel_lib_dir = tauon_ecos_lib_dir + 'bin/'
tauon_kernel_obj_dir = k60n512_prj_dir + 'arch/cortexm/k60n512/obj/'

#export source files
Export('tauon_kernel_src_list')
Export('tauon_kernel_lib_dir')
Export('tauon_kernel_obj_dir')
Export('tauon_ecos_install_dir')
